---
title: "suspect_victim_correlations"
author: "Nihaal Rahman"
output: github_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message=FALSE,
  warning=FALSE)
library(tidyverse)
library(tidyr)
library(gridExtra)
```

```{r,include=FALSE}
df_nypd = read_csv("https://www.dropbox.com/scl/fi/kf2zk4t1onxzm2vo3lpkq/NYPD_Complaint_Data_Historic.csv?rlkey=ly36vi9v66sno80eir6rohlwn&dl=1", na = "(null)") |>
  janitor::clean_names() 

data=df_nypd|>
  select(law_cat_cd,susp_age_group,susp_race,susp_sex,vic_age_group,vic_race,vic_sex)|>
  mutate_all(~na_if(.,"UNKNOWN"))|>
  na.omit()
```

Looking at suspect/victim age by level of offense
```{r}
age_combined <- gather(data, key = "variable", value = "age", susp_age_group, vic_age_group)

age_plot <- data |> 
  filter(susp_age_group %in% c('<18', '18-24', '25-44', '45-64', '65+') & vic_age_group %in% c('<18', '18-24', '25-44', '45-64', '65+')) |> 
  gather(key = "variable", value = "age", susp_age_group, vic_age_group) |> 
  ggplot(aes(x = law_cat_cd, fill = age)) +
  geom_bar(position = "dodge") +
  labs(title = "Distribution of suspect and victim age by level of offense") +
  guides(fill = guide_legend(title = "Age")) +
  facet_wrap(~variable, scales = "free_x", ncol = 2) +
  theme(legend.position = "bottom")

print(age_plot)
```

Looking at suspect/victim sex by level of offense
```{r}
sex_combined <- gather(data, key = "variable", value = "sex", susp_sex, vic_sex)

sex_plot <- data |> 
  filter(susp_sex %in% c('F', 'M') & vic_sex %in% c('F', 'M')) |> 
  gather(key = "variable", value = "sex", susp_sex, vic_sex) |> 
  ggplot(aes(x = law_cat_cd, fill = sex)) +
  geom_bar(position = "dodge") +
  labs(title = "Distribution of suspect and victim sex by level of offense") +
  guides(fill = guide_legend(title = "Sex")) +
  facet_wrap(~variable, scales = "free_x", ncol = 2) +
  theme(legend.position = "bottom")

print(sex_plot)
```

Looking at suspect/victim race by level of offense
```{r}
race_combined <- gather(data, key = "variable", value = "race", susp_race, vic_race)

race_plot <- ggplot(race_combined, aes(x = law_cat_cd, fill = race)) +
  geom_bar(position = "dodge") +
  labs(title = "Distribution of supect and victim race by level of offense") +
  guides(fill = guide_legend(title = "Race")) +
  facet_wrap(~variable, scales = "free_x", ncol = 2) +
  theme(legend.position = "bottom") 

print(race_plot)
```

Seeing which combination of race+age+sex has the highest counts for victim and suspects
```{r}
victim_count <- data |> 
  filter(vic_sex %in% c('F', 'M')) |> 
  filter(vic_age_group %in% c('<18', '18-24', '25-44', '45-64', '65+')) |> 
  select(vic_age_group, vic_race, vic_sex) |> 
  group_by(vic_age_group, vic_race, vic_sex) |> 
  summarize(count = n()) |> 
  ungroup() |> 
  arrange(desc(count))
  
print(victim_count)

suspect_count <- data |> 
  filter(susp_sex %in% c('F', 'M')) |> 
  filter(susp_age_group %in% c('<18', '18-24', '25-44', '45-64', '65+')) |> 
  select(susp_age_group, susp_race, susp_sex) |> 
  group_by(susp_age_group, susp_race, susp_sex) |> 
  summarize(count = n()) |> 
  ungroup() |> 
  arrange(desc(count))
  
print(suspect_count)
```


