---
title: "DataProcessing_GeneralCrimeData"
author: "Xinyi Shang"
date: "2023-12-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(lubridate)
library(htmltools)

```

```{r load code ,echo=FALSE}
#df_nypd = read_csv("https://www.dropbox.com/scl/fi/kf2zk4t1onxzm2vo3lpkq/NYPD_Complaint_Data_Historic.csv?rlkey=ly36vi9v66sno80eir6rohlwn&dl=1", na = "(null)") |>
#  janitor::clean_names()

df_nypd = read_csv('data/NYPD_Complaint_Data_Historic.csv') |>
  janitor::clean_names()

```

```{r divide data by years}
df_nypd_test <- df_nypd  %>%
  janitor::clean_names() %>%
  mutate(cmplnt_fr_dt = lubridate::mdy(cmplnt_fr_dt)) |>
  select(cmplnt_fr_dt, ofns_desc, boro_nm) 

data_2017 <- df_nypd_test %>%
  filter(year(cmplnt_fr_dt) == 2017)

data_2018 <- df_nypd_test %>%
  filter(year(cmplnt_fr_dt) == 2018)

data_2019 <- df_nypd_test %>%
  filter(year(cmplnt_fr_dt) == 2019)

data_2020 <- df_nypd_test %>%
  filter(year(cmplnt_fr_dt) == 2020)

data_2021 <- df_nypd_test %>%
  filter(year(cmplnt_fr_dt) == 2021)

data_2022 <- df_nypd_test %>%
  filter(year(cmplnt_fr_dt) == 2022)
```

```{r data processing for top 10 crime types}
# Create a function to generate top 10 crime types for each year
get_top_10_crimes_byboro <- function(data, year) {
    result <- data %>%
    group_by(boro_nm, ofns_desc) %>%
    summarise(Incident_Count = n()) %>%
    arrange(boro_nm, desc(Incident_Count)) %>%
    group_by(boro_nm) %>%
    slice_head(n = 10) %>%
    mutate(year = year) %>%
    filter(boro_nm != "(null)")
  return(result)
}

get_top_10_crimes = function(data, year)  {
    result <- data %>%
    group_by(ofns_desc) %>%
    summarise(Incident_Count = n()) %>%
    arrange(desc(Incident_Count)) %>%
    slice_head(n = 10) %>%
    mutate(year = year) %>%
    mutate(boro_nm = "Overall")|>
    group_by(boro_nm)|>
    bind_rows(get_top_10_crimes_byboro(data, year))
  return(result)
}

crime_counts_overall = get_top_10_crimes(df_nypd_test, 0000) #use 0000 to represent overall
crime_counts_2017 <- get_top_10_crimes(data_2017,2017)
crime_counts_2018 <- get_top_10_crimes(data_2018,2018)
crime_counts_2019 <- get_top_10_crimes(data_2019,2019)
crime_counts_2020 <- get_top_10_crimes(data_2020,2020)
crime_counts_2021 <- get_top_10_crimes(data_2021,2021)
crime_counts_2022 <- get_top_10_crimes(data_2022,2022)


crime_counts = bind_rows(crime_counts_overall, crime_counts_2017,crime_counts_2018,crime_counts_2019,crime_counts_2020,crime_counts_2021,crime_counts_2022)

write.csv(crime_counts, "Top10CrimeTypes/data/crime_counts.csv", row.names = FALSE)
```






